[tool.poetry]
name = "quarto-progress-bar"
version = "0.1.0"
description = ""
authors = ["errbufferoverfl <merrymet@errbufferoverfl.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
